### ISSUE TITLE
Rename CMS LHD 2021 to HackCamp 2020

### ISSUE THREAD

**Issue by acchiang** [nwplus/cms#48]
CMS's mentions of LHD should be updated to HackCamp 2020 (not LHD or 2021)! Thank y'all! 
@Ciuffi please reassign to a Dev :)

![image](https://user-images.githubusercontent.com/47487758/98592738-01240800-2287-11eb-81b1-8d4bd125cbb1.png)

**Comment by Ciuffi** [comment]
@kozr this name is based on the collection name in firebase, am I safe to change it to hackcamp2020 or will this break frontend things?

**Comment by kozr** [comment]
It will break

**Comment by kozr** [comment]
Im very busy this week so won't have time to refactor the frontend for now

**Comment by acchiang** [comment]
it's an internal tool so no big deal, we can delay this as long as it's on your radar

**Comment by acchiang** [comment]
closing as per slack discussion
